projects:
  marketing:
    schema: './apps/marketing/gql/schema.graphql'
    documents:
      [
        'apps/marketing/app/**/*.{graphql,js,ts,jsx,tsx}',
        'apps/marketing/components/**/*.{graphql,js,ts,jsx,tsx}',
        'apps/marketing/lib/**/*.{graphql,js,ts,jsx,tsx}',
      ]
