/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n    query PageSlugQuery($slug: String, $locale: String, $preview: Boolean) {\n      pageCollection(locale: $locale, preview: $preview, limit: 1, where: { slug: $slug }) {\n        items {\n          slug\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ pageCollection: { items: ({ slug: string | null; } | null)[]; } | null; }, { preview?: boolean | null | undefined; locale?: string | null | undefined; slug?: string | null | undefined; }, void>;
    "\n  fragment AssetFields on Asset {\n    __typename\n    sys {\n      id\n    }\n    contentType\n    title\n    url\n    width\n    height\n    description\n  }\n":
      TadaDocumentNode<{ __typename: "Asset"; sys: { id: string; }; contentType: string | null; title: string | null; url: string | null; width: number | null; height: number | null; description: string | null; }, {}, { fragment: "AssetFields"; on: "Asset"; masked: true; }>;
    "\n  fragment ComponentForm on ComponentForm {\n    __typename\n    sys {\n      id\n    }\n  }\n":
      TadaDocumentNode<{ __typename: "ComponentForm"; sys: { id: string; }; }, {}, { fragment: "ComponentForm"; on: "ComponentForm"; masked: true; }>;
    "\n  fragment PageLinkFields on Page {\n    __typename\n    slug\n    sys {\n      id\n    }\n    pageName\n    pageContent(locale: $locale, preview: $preview) {\n      ... on Entry {\n        __typename\n        sys {\n          id\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ __typename: "Page"; slug: string | null; sys: { id: string; }; pageName: string | null; pageContent: { __typename: "ComponentDuplex"; sys: { id: string; }; } | { __typename: "ComponentProductTable"; sys: { id: string; }; } | { __typename: "TopicBusinessInfo"; sys: { id: string; }; } | { __typename: "TopicProduct"; sys: { id: string; }; } | null; }, {}, { fragment: "PageLinkFields"; on: "Page"; masked: true; }>;
    "\n    fragment TopicPerson on TopicPerson {\n      __typename\n      sys {\n        id\n      }\n      name\n      website\n      location\n      cardStyle\n      bio {\n        json\n      }\n      avatar {\n        ...AssetFields\n      }\n    }\n  ":
      TadaDocumentNode<{ __typename: "TopicPerson"; sys: { id: string; }; name: string | null; website: string | null; location: string | null; cardStyle: boolean | null; bio: { json: unknown; } | null; avatar: { [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null; }, {}, { fragment: "TopicPerson"; on: "TopicPerson"; masked: true; }>;
    "\n    fragment ComponentHeroBannerFields on ComponentHeroBanner {\n      __typename\n      sys {\n        id\n      }\n      headline\n      bodyText {\n        json\n        links {\n          assets {\n            block {\n              ...AssetFields\n            }\n          }\n        }\n      }\n      ctaText\n      targetPage {\n        ...PageLinkFields\n      }\n      image {\n        ...AssetFields\n      }\n      imageStyle\n      heroSize\n      colorPalette\n    }\n  ":
      TadaDocumentNode<{ __typename: "ComponentHeroBanner"; sys: { id: string; }; headline: string | null; bodyText: { json: unknown; links: { assets: { block: ({ [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null)[]; }; }; } | null; ctaText: string | null; targetPage: { __typename?: "Page" | undefined; [$tada.fragmentRefs]: { PageLinkFields: "Page"; }; } | null; image: { [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null; imageStyle: boolean | null; heroSize: boolean | null; colorPalette: string | null; }, {}, { fragment: "ComponentHeroBannerFields"; on: "ComponentHeroBanner"; masked: true; }>;
    "\n    fragment ComponentDuplexFields on ComponentDuplex {\n      __typename\n      sys {\n        id\n      }\n      headline\n      bodyText {\n        json\n      }\n      ctaText\n      targetPage {\n        ...PageLinkFields\n      }\n      image {\n        ...AssetFields\n      }\n      imageStyle\n      colorPalette\n      containerLayout\n    }\n  ":
      TadaDocumentNode<{ __typename: "ComponentDuplex"; sys: { id: string; }; headline: string | null; bodyText: { json: unknown; } | null; ctaText: string | null; targetPage: { __typename?: "Page" | undefined; [$tada.fragmentRefs]: { PageLinkFields: "Page"; }; } | null; image: { [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null; imageStyle: boolean | null; colorPalette: string | null; containerLayout: boolean | null; }, {}, { fragment: "ComponentDuplexFields"; on: "ComponentDuplex"; masked: true; }>;
    "\n    fragment TopicBusinessInfo on TopicBusinessInfo {\n      __typename\n      sys {\n        id\n      }\n      name\n      shortDescription\n      body {\n        json\n        links {\n          entries {\n            block {\n              ...TopicPerson\n            }\n          }\n        }\n      }\n      featuredImage {\n        ...AssetFields\n      }\n    }\n  ":
      TadaDocumentNode<{ __typename: "TopicBusinessInfo"; sys: { id: string; }; name: string | null; shortDescription: string | null; body: { json: unknown; links: { entries: { block: ({ __typename?: "Page" | undefined; } | { __typename?: "Accordion" | undefined; } | { __typename?: "AccordionItem" | undefined; } | { __typename?: "ComponentCta" | undefined; } | { __typename?: "ComponentDuplex" | undefined; } | { __typename?: "ComponentForm" | undefined; } | { __typename?: "ComponentHeroBanner" | undefined; } | { __typename?: "ComponentInfoBlock" | undefined; } | { __typename?: "ComponentProductTable" | undefined; } | { __typename?: "ComponentQuote" | undefined; } | { __typename?: "ComponentTextBlock" | undefined; } | { __typename?: "FooterMenu" | undefined; } | { __typename?: "MenuGroup" | undefined; } | { __typename?: "NavigationMenu" | undefined; } | { __typename?: "Seo" | undefined; } | { __typename?: "TopicBusinessInfo" | undefined; } | { __typename?: "TopicPerson" | undefined; [$tada.fragmentRefs]: { TopicPerson: "TopicPerson"; }; } | { __typename?: "TopicProduct" | undefined; } | { __typename?: "TopicProductFeature" | undefined; } | null)[]; }; }; } | null; featuredImage: { [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null; }, {}, { fragment: "TopicBusinessInfo"; on: "TopicBusinessInfo"; masked: true; }>;
    "\n    fragment MenuGroupFields on MenuGroupFeaturedPagesCollection {\n      items {\n        ...PageLinkFields\n      }\n    }\n  ":
      TadaDocumentNode<{ items: ({ __typename?: "Page" | undefined; [$tada.fragmentRefs]: { PageLinkFields: "Page"; }; } | null)[]; }, {}, { fragment: "MenuGroupFields"; on: "MenuGroupFeaturedPagesCollection"; masked: true; }>;
    "\n    fragment NavigationFields on NavigationMenuCollection {\n      items {\n        menuItemsCollection {\n          items {\n            __typename\n            sys {\n              id\n            }\n            groupName\n            link: groupLink {\n              ...PageLinkFields\n            }\n            children: featuredPagesCollection {\n              ...MenuGroupFields\n            }\n          }\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ items: ({ menuItemsCollection: { items: ({ __typename: "MenuGroup"; sys: { id: string; }; groupName: string | null; link: { __typename?: "Page" | undefined; [$tada.fragmentRefs]: { PageLinkFields: "Page"; }; } | null; children: { [$tada.fragmentRefs]: { MenuGroupFields: "MenuGroupFeaturedPagesCollection"; }; } | null; } | null)[]; } | null; } | null)[]; }, {}, { fragment: "NavigationFields"; on: "NavigationMenuCollection"; masked: true; }>;
    "\n      query Layout($locale: String, $preview: Boolean) {\n        navigationMenuCollection(locale: $locale, preview: $preview, limit: 1) {\n          ...NavigationFields\n        }\n      }\n    ":
      TadaDocumentNode<{ navigationMenuCollection: { [$tada.fragmentRefs]: { NavigationFields: "NavigationMenuCollection"; }; } | null; }, { preview?: boolean | null | undefined; locale?: string | null | undefined; }, void>;
    "\n    fragment SEOFields on Seo {\n      __typename\n      sys {\n        id\n      }\n      title\n      description\n      noIndex\n      noFollow\n      image {\n        ...AssetFields\n      }\n    }\n  ":
      TadaDocumentNode<{ __typename: "Seo"; sys: { id: string; }; title: string | null; description: string | null; noIndex: boolean | null; noFollow: boolean | null; image: { [$tada.fragmentRefs]: { AssetFields: "Asset"; }; } | null; }, {}, { fragment: "SEOFields"; on: "Seo"; masked: true; }>;
    "\n    query PageQuery($slug: String, $locale: String, $preview: Boolean) {\n      pageCollection(locale: $locale, preview: $preview, limit: 1, where: { slug: $slug }) {\n        items {\n          slug\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ pageCollection: { items: ({ slug: string | null; } | null)[]; } | null; }, { preview?: boolean | null | undefined; locale?: string | null | undefined; slug?: string | null | undefined; }, void>;
    "\n      query PageQuery($slug: String, $locale: String, $preview: Boolean) @contentSourceMaps {\n        pageCollection(locale: $locale, preview: $preview, limit: 1, where: { slug: $slug }) {\n          items {\n            topSectionCollection(limit: 10) {\n              items {\n                __typename\n                ... on Entry {\n                  sys {\n                    id\n                  }\n                }\n                ...ComponentHeroBannerFields\n                ...ComponentDuplexFields\n              }\n            }\n            pageContent {\n              __typename\n              ... on Entry {\n                sys {\n                  id\n                }\n              }\n              ...TopicBusinessInfo\n            }\n            slugEn: slug(locale: \"en-US\")\n            slugDe: slug(locale: \"de-DE\")\n          }\n        }\n      }\n    ":
      TadaDocumentNode<{ pageCollection: { items: ({ topSectionCollection: { items: ({ __typename: "Accordion"; sys: { id: string; }; } | { __typename: "ComponentCta"; sys: { id: string; }; } | { __typename: "ComponentDuplex"; sys: { id: string; }; [$tada.fragmentRefs]: { ComponentDuplexFields: "ComponentDuplex"; }; } | { __typename: "ComponentForm"; sys: { id: string; }; } | { __typename: "ComponentHeroBanner"; sys: { id: string; }; [$tada.fragmentRefs]: { ComponentHeroBannerFields: "ComponentHeroBanner"; }; } | { __typename: "ComponentInfoBlock"; sys: { id: string; }; } | { __typename: "ComponentQuote"; sys: { id: string; }; } | { __typename: "ComponentTextBlock"; sys: { id: string; }; } | null)[]; } | null; pageContent: { __typename: "ComponentDuplex"; sys: { id: string; }; } | { __typename: "ComponentProductTable"; sys: { id: string; }; } | { __typename: "TopicBusinessInfo"; sys: { id: string; }; [$tada.fragmentRefs]: { TopicBusinessInfo: "TopicBusinessInfo"; }; } | { __typename: "TopicProduct"; sys: { id: string; }; } | null; slugEn: string | null; slugDe: string | null; } | null)[]; } | null; }, { preview?: boolean | null | undefined; locale?: string | null | undefined; slug?: string | null | undefined; }, void>;
    "\n    query PageSlugs($locale: String) {\n      # Fetch 50 pages. Ideally we would fetch a good sample of most popular pages for pre-rendering,\n      # but for the sake of this example we'll just fetch the first 50.\n      pageCollection(locale: $locale, limit: 50) {\n        items {\n          slug\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ pageCollection: { items: ({ slug: string | null; } | null)[]; } | null; }, { locale?: string | null | undefined; }, void>;
    "\n      query PageQuery($slug: String, $locale: String, $preview: Boolean) {\n        pageCollection(locale: $locale, preview: $preview, limit: 1, where: { slug: $slug }) {\n          items {\n            seo {\n              ...SEOFields\n            }\n            slugEn: slug(locale: \"en-US\")\n            slugDe: slug(locale: \"de-DE\")\n          }\n        }\n      }\n    ":
      TadaDocumentNode<{ pageCollection: { items: ({ seo: { [$tada.fragmentRefs]: { SEOFields: "Seo"; }; } | null; slugEn: string | null; slugDe: string | null; } | null)[]; } | null; }, { preview?: boolean | null | undefined; locale?: string | null | undefined; slug?: string | null | undefined; }, void>;
  }
}
